set -e
sudo apt -y install python3-venv # Install python virtual environment (If not already installed)
sudo apt install libnginx-mod-http-fancyindex
#sudo apt -y install sqlite3 sqlite3-doc sqlite3-tools
python3 -m venv venv # Create an virtual Python environment
. venv/bin/activate # Activate the environment - Use deactivate to exit the virtual environment
pip install --upgrade pip wheel setuptools requests
pip install flask[async]
#pip install turbo_flask
pip install Flask-Nav
pip install flask-bootstrap
pip install flask-socketio
pip install gunicorn
pip install nats-py
pip install pyyaml
echo "Remember to active virtual environment with 'source venv/bin/activte'"
echo "See: https://medium.com/@abhishekchaudhary_28536/building-apps-using-flask-socketio-and-javascript-socket-io-part-1-ae448768643#id_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjY3NmRhOWQzMTJjMzlhNDI5OTMyZjU0M2U2YzFiNmU2NTEyZTQ5ODMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20iLCJuYmYiOjE2ODkwMDI0MjksImF1ZCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsInN1YiI6IjExMzgyMjM1ODA3NTQ2OTc5MTA1MSIsImVtYWlsIjoidGplbGVoZW5yaWtAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImF6cCI6IjIxNjI5NjAzNTgzNC1rMWs2cWUwNjBzMnRwMmEyamFtNGxqZGNtczAwc3R0Zy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbSIsIm5hbWUiOiJIZW5yaWsgVGhvbXNlbiIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQWNIVHRlQXVlenZKUzZUMzBRTVVxVEswQ3NYMlBOZEltRGVjSG9LUDBBZ3RRZTRrYjg9czk2LWMiLCJnaXZlbl9uYW1lIjoiSGVucmlrIiwiZmFtaWx5X25hbWUiOiJUaG9tc2VuIiwiaWF0IjoxNjg5MDAyNzI5LCJleHAiOjE2ODkwMDYzMjksImp0aSI6IjM1YjQ2NzMwZWU3OTdjNWE3ZDYyMWEzZTYxNTE1ZDhhZDMxMGM5YjcifQ.KueMa6v1bBG6_GlJyZUulIf31NyM210_uW_yVDZnTi0NtibqlolrXmNC_A-ltre92KO_z30SJYFTxBXMKIK_rPCf751jo3g7JEg_s_y0sosaxOGSw444n-i26F1pGg41M3ed2NrtVuRsDIWaHnWcrG94ygnMtL-vC6O6LEq29wmroXZKggSetXtDmtGxzYgG7JTtgHFMuEf1fcENYWd8h5d5oopukQbMY2bDol6uhpns4TqcVm5m1W69EGiUByHvJAOwMJiDd4TWgqJwh8lNWoA5dS3slgzGiDLGFI3A3op372c6SqlWCCmKedVDNEjF_JZxBzKQyafK0CRNHxqa3Q"
#flask --debug --app ws1.py run --host=0.0.0.0
# not necesary only with flask_nav pip install flask_bootstrap

#  vi /home/heth/flask/mbusV3/venv/lib/python3.10/site-packages/flask_nav/__init__.py
# change import collections to import collections.abc as collections

