#!/usr/bin/env bash
USER=debian
if [ $EUID -ne 0 ]
then
        echo -e "ERROR: You need root credentials to run this script"
        exit
fi

sudo apt -y update
sudo apt -y upgrade
sudo -H -u $USER cp vimrc /home/$USER/.vimrc
./install-stage1-libmbus
