#!/usr/bin/env bash
if [ $EUID -ne 0 ]
then
        echo -e "ERROR: You need root credentials to run this script"
        exit
fi

sudo apt -y update
sudo apt -y upgrade

LIST="man-db build-essential manpages-dev glibc-doc dpkg-dev linux-doc
        user-mode-linux-doc libssl-dev docbook docbook-xml devscripts
        docbook-xsl xsltproc libsystemd-dev libltdl-dev libcjson1
        libcjson-dev libltdl-dev gdb tmux"
LOGFILE="./apt-install.log"
echo "" > $LOGFILE
DIRTY=0

for PACK in $LIST
do
        printf "Installerer %s\n" $PACK
        if apt -y install $PACK
        then
                printf "Package %s OK\n" $PACK >> $LOGFILE
        else
                printf "Package %s FAILED......................\n" $PACK >> $LOGFILE
                let DIRTY=DIRTY+1
        fi
done
printf "\n\n**************************************************\n"
if test $DIRTY -eq 0
then
        printf "Seems all look good - all packages OK\n"
else
        printf "ERROR: %d packages failed - see logfile: %s\n" $DIRTY $LOGFILE
fi
printf "**************************************************\n"
echo "================================================================"
echo "To install and prepare device for M-bus: sudo ./install-stage2"
echo "================================================================"

